version: "3"

services:
  pg_master:
    build: ./master
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=adminpostgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=testdb
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=rep123456

    networks:
      default:
      aliases:
        - pg_cluster

  pg_slave:
    build: ./slave
    environment:
      - POSTGRES_USER=adminpostgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=testdb
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=rep123456
    networks:
      default:
      aliases:
        - pg_cluster
        
volumes:
  pg_data:
